-- ============================================================
-- JeeVan — Complete Seed Data (50+ plants, 10 categories)
-- Paste into Supabase SQL Editor AFTER schema.sql
-- ============================================================

DELETE FROM admin_users;
INSERT INTO admin_users (id, username, passkey_hash, admin_tier, assigned_ventures) VALUES
  ('91532c20-863c-4380-9ddd-6e52816370d1','shubham','$2b$12$dI9d9e/jNFhcFta/e5hhEOdJO.czpTBHaY0QtzdkcFB9xC1lOkerC','ALPHA','["nursery","gardening","tech","studio","marketplace"]'),
  (gen_random_uuid(),'partner_nursery','$2b$12$LfICbuxfqO0TdH15EB8Dwuumi/agaoWqz.G5X7RDM5fOT7yVl7rIC','BETA','["nursery"]');

-- 1: STAPLE FOOD CROPS (7 plants)
INSERT INTO plant_directory (botanical_name, common_name, category, sub_category, origin_regions, optimal_climate, soil_requirements, growth_cycle_days, water_needs, description) VALUES
('Oryza sativa','Rice (Basmati)','staple','Cereal','["South Asia"]','{"temp_min":20,"temp_max":35,"rainfall_min":1000,"rainfall_max":2000}','{"ph_min":5.5,"ph_max":7.0,"type":["clay","loam"],"drainage":"poor"}',120,'High','Aromatic long-grain rice. Thrives in flooded paddies. India produces 70% of world basmati.'),
('Triticum durum','Wheat (Durum)','staple','Cereal','["Fertile Crescent"]','{"temp_min":10,"temp_max":25,"rainfall_min":400,"rainfall_max":800}','{"ph_min":6.0,"ph_max":7.5,"type":["loam","clay loam"],"drainage":"well"}',150,'Medium','Hard wheat for semolina/pasta. Rabi crop in North India.'),
('Zea mays','Maize (Corn)','staple','Cereal','["Mesoamerica"]','{"temp_min":18,"temp_max":32,"rainfall_min":500,"rainfall_max":1000}','{"ph_min":5.8,"ph_max":7.0,"type":["loam","sandy loam"],"drainage":"well"}',90,'Medium-High','Versatile cereal. Grown in Kharif and Rabi.'),
('Pennisetum glaucum','Pearl Millet (Bajra)','staple','Millet','["Sahel Africa","South Asia"]','{"temp_min":25,"temp_max":40,"rainfall_min":200,"rainfall_max":600}','{"ph_min":6.0,"ph_max":8.0,"type":["sandy loam"],"drainage":"well"}',75,'Low','Drought-resistant. High iron and protein. Rajasthan and Haryana staple.'),
('Eleusine coracana','Finger Millet (Ragi)','staple','Millet','["East Africa","South Asia"]','{"temp_min":18,"temp_max":30,"rainfall_min":500,"rainfall_max":1000}','{"ph_min":5.0,"ph_max":7.5,"type":["loam","sandy loam"],"drainage":"well"}',120,'Medium','Exceptionally high calcium. Karnataka and Tamil Nadu staple.'),
('Cajanus cajan','Pigeon Pea (Arhar/Tur)','staple','Pulse','["Indian Subcontinent"]','{"temp_min":18,"temp_max":30,"rainfall_min":600,"rainfall_max":1000}','{"ph_min":5.0,"ph_max":7.0,"type":["loam","sandy loam"],"drainage":"well"}',180,'Medium','Major protein source. Nitrogen-fixing. India produces 80% of world supply.'),
('Cicer arietinum','Chickpea (Chana)','staple','Pulse','["Middle East","South Asia"]','{"temp_min":15,"temp_max":25,"rainfall_min":300,"rainfall_max":600}','{"ph_min":6.0,"ph_max":7.5,"type":["loam","clay loam"],"drainage":"well"}',120,'Low-Medium','Rabi pulse crop. Desi and Kabuli varieties. Madhya Pradesh leads production.');

-- 2: PRODUCE — Vegetables, Fruits & Nuts (10 plants)
INSERT INTO plant_directory (botanical_name, common_name, category, sub_category, exotic_variety, heirloom, origin_regions, optimal_climate, soil_requirements, growth_cycle_days, water_needs, description) VALUES
('Solanum lycopersicum','Heirloom Tomato','produce','Vegetable',FALSE,TRUE,'["Andes"]','{"temp_min":18,"temp_max":30,"rainfall_min":400,"rainfall_max":800}','{"ph_min":6.0,"ph_max":6.8,"type":["loam"],"drainage":"well"}',80,'Medium','Non-hybrid with superior flavor and seed-saving.'),
('Moringa oleifera','Moringa (Drumstick)','produce','Tree Vegetable',FALSE,FALSE,'["Indian Subcontinent"]','{"temp_min":25,"temp_max":40,"rainfall_min":300,"rainfall_max":1200}','{"ph_min":6.0,"ph_max":7.5,"type":["sandy loam"],"drainage":"well"}',240,'Low-Medium','Leaves, pods, flowers all edible. Grown at JeeVan Farms, Nalanda.'),
('Abelmoschus esculentus','Okra (Bhindi)','produce','Vegetable',FALSE,FALSE,'["East Africa","South Asia"]','{"temp_min":22,"temp_max":35,"rainfall_min":500,"rainfall_max":1200}','{"ph_min":6.0,"ph_max":7.5,"type":["sandy loam"],"drainage":"well"}',55,'Medium','Fast-growing summer vegetable. Popular across Indian cuisine.');

INSERT INTO plant_directory (botanical_name, common_name, category, sub_category, origin_regions, optimal_climate, soil_requirements, growth_cycle_days, water_needs, description) VALUES
('Phyllanthus emblica','Amla (Gooseberry)','produce','Fruit','["India"]','{"temp_min":15,"temp_max":35,"rainfall_min":600,"rainfall_max":1500}','{"ph_min":6.0,"ph_max":8.0,"type":["loam","sandy loam"],"drainage":"well"}',180,'Medium','Single fruit = Vitamin C of 20 oranges. Ayurvedic essential.'),
('Mangifera indica','Mango (Aam)','produce','Fruit','["India"]','{"temp_min":24,"temp_max":35,"rainfall_min":500,"rainfall_max":2500}','{"ph_min":5.5,"ph_max":7.5,"type":["loam"],"drainage":"well"}',365,'Medium','India produces 50% of world mangoes. Bihar: Malda, Langra, Dasheri.'),
('Musa paradisiaca','Banana (Kela)','produce','Fruit','["Southeast Asia"]','{"temp_min":20,"temp_max":35,"rainfall_min":1000,"rainfall_max":2500}','{"ph_min":5.5,"ph_max":7.5,"type":["loam","clay loam"],"drainage":"well"}',300,'High','Year-round crop. Rich in potassium. Bihar: G9 and Malbhog varieties.'),
('Citrus limon','Lemon (Nimbu)','produce','Fruit','["South Asia"]','{"temp_min":15,"temp_max":30,"rainfall_min":500,"rainfall_max":1500}','{"ph_min":5.5,"ph_max":6.5,"type":["loam"],"drainage":"well"}',180,'Medium','Year-round citrus. Kitchen garden essential.'),
('Psidium guajava','Guava (Amrud)','produce','Fruit','["Central America","India"]','{"temp_min":15,"temp_max":35,"rainfall_min":500,"rainfall_max":2000}','{"ph_min":5.0,"ph_max":7.0,"type":["loam","sandy loam"],"drainage":"well"}',240,'Medium','Allahabad Safeda and L-49 varieties. Year-round fruiting in Bihar.'),
('Carica papaya','Papaya (Papita)','produce','Fruit','["Central America"]','{"temp_min":20,"temp_max":35,"rainfall_min":1000,"rainfall_max":2000}','{"ph_min":6.0,"ph_max":7.0,"type":["loam","sandy loam"],"drainage":"well"}',240,'Medium-High','Fast-growing. Red Lady and Pusa Dwarf varieties. Fruiting in 9 months.'),
('Anacardium occidentale','Cashew (Kaju)','produce','Nut','["Brazil","India"]','{"temp_min":20,"temp_max":35,"rainfall_min":1000,"rainfall_max":3500}','{"ph_min":5.0,"ph_max":6.5,"type":["sandy loam","laterite"],"drainage":"well"}',1095,'Medium','India is 2nd largest producer. Thrives in coastal regions. 3 years to first harvest.');

-- 3: BEVERAGES, SPICES & STIMULANTS (7 plants)
INSERT INTO plant_directory (botanical_name, common_name, category, sub_category, origin_regions, optimal_climate, soil_requirements, growth_cycle_days, water_needs, description) VALUES
('Ocimum sanctum','Tulsi (Holy Basil)','beverages','Herb','["India"]','{"temp_min":15,"temp_max":35,"rainfall_min":300,"rainfall_max":1000}','{"ph_min":6.0,"ph_max":7.5,"type":["loam"],"drainage":"well"}',60,'Medium','Adaptogenic herb. Rama and Krishna varieties. Every Indian home should grow.'),
('Curcuma longa','Turmeric (Haldi)','beverages','Spice','["South Asia"]','{"temp_min":20,"temp_max":35,"rainfall_min":1000,"rainfall_max":2000}','{"ph_min":5.5,"ph_max":7.5,"type":["clay loam"],"drainage":"well"}',240,'High','India produces 80% of world turmeric. Anti-inflammatory curcumin. 7-9 month crop.'),
('Cymbopogon citratus','Lemongrass','beverages','Herb','["Southeast Asia"]','{"temp_min":20,"temp_max":35,"rainfall_min":700,"rainfall_max":3000}','{"ph_min":5.0,"ph_max":8.0,"type":["loam"],"drainage":"well"}',90,'Medium-High','Aromatic grass for teas and essential oils. Easy to grow, highly productive.'),
('Zingiber officinale','Ginger (Adrak)','beverages','Spice','["Southeast Asia"]','{"temp_min":20,"temp_max":30,"rainfall_min":1500,"rainfall_max":2500}','{"ph_min":5.5,"ph_max":6.5,"type":["loam","clay loam"],"drainage":"well"}',210,'High','Major spice crop. Kerala and NE India lead production.'),
('Piper nigrum','Black Pepper (Kali Mirch)','beverages','Spice','["Western Ghats","India"]','{"temp_min":20,"temp_max":35,"rainfall_min":2000,"rainfall_max":4000}','{"ph_min":5.0,"ph_max":6.5,"type":["clay loam"],"drainage":"well"}',1095,'High','King of Spices. Vine crop. Kerala Malabar variety is world-renowned.'),
('Elettaria cardamomum','Cardamom (Elaichi)','beverages','Spice','["Western Ghats","India"]','{"temp_min":10,"temp_max":35,"rainfall_min":1500,"rainfall_max":4000}','{"ph_min":4.5,"ph_max":6.5,"type":["forest loam"],"drainage":"well"}',730,'High','Queen of Spices. 2nd most expensive spice after saffron. Shade-loving.'),
('Camellia sinensis','Tea (Chai)','beverages','Beverage','["China","India"]','{"temp_min":15,"temp_max":30,"rainfall_min":1500,"rainfall_max":4000}','{"ph_min":4.5,"ph_max":5.5,"type":["loam","sandy loam"],"drainage":"well"}',1095,'High','Assam and Darjeeling are global icons. Requires acidic soil and high elevation.');

-- 4: ORNAMENTAL & LANDSCAPING (5 plants)
INSERT INTO plant_directory (botanical_name, common_name, category, sub_category, origin_regions, optimal_climate, soil_requirements, growth_cycle_days, water_needs, description) VALUES
('Tagetes erecta','Marigold (Genda)','ornamental','Flower','["Mexico"]','{"temp_min":18,"temp_max":30,"rainfall_min":300,"rainfall_max":800}','{"ph_min":6.0,"ph_max":7.5,"type":["loam"],"drainage":"well"}',55,'Low','Festival essential. Natural pest repellent. Intercrop with vegetables.'),
('Rosa indica','Desi Rose (Gulab)','ornamental','Flower','["India","Middle East"]','{"temp_min":10,"temp_max":28,"rainfall_min":400,"rainfall_max":800}','{"ph_min":6.0,"ph_max":7.0,"type":["loam","clay loam"],"drainage":"well"}',90,'Medium','Fragrant Indian rose adapted to local climate. Year-round blooms.'),
('Hibiscus rosa-sinensis','Hibiscus (Gudhal)','ornamental','Flower','["East Asia"]','{"temp_min":15,"temp_max":35,"rainfall_min":400,"rainfall_max":1200}','{"ph_min":6.0,"ph_max":7.5,"type":["loam"],"drainage":"well"}',180,'Medium','Large spectacular flowers. Medicinal properties. Low maintenance.'),
('Ficus religiosa','Peepal Tree','ornamental','Shade Tree','["Indian Subcontinent"]','{"temp_min":15,"temp_max":40,"rainfall_min":500,"rainfall_max":2500}','{"ph_min":6.0,"ph_max":8.0,"type":["all"],"drainage":"well"}',3650,'Low','Sacred tree. Massive canopy. Can live 1000+ years. Excellent shade and oxygen.'),
('Azadirachta indica','Neem Tree','ornamental','Shade Tree','["Indian Subcontinent"]','{"temp_min":20,"temp_max":40,"rainfall_min":400,"rainfall_max":1200}','{"ph_min":5.0,"ph_max":8.0,"type":["all"],"drainage":"all"}',1825,'Low','Natural pesticide, medicine, timber. Every part of neem has commercial value.');

-- 5: FARMING SUPPORT CROPS (3 plants)
INSERT INTO plant_directory (botanical_name, common_name, category, sub_category, origin_regions, optimal_climate, soil_requirements, growth_cycle_days, water_needs, description) VALUES
('Crotalaria juncea','Sunn Hemp (Sanai)','cover','Green Manure','["Indian Subcontinent"]','{"temp_min":20,"temp_max":35,"rainfall_min":400,"rainfall_max":1000}','{"ph_min":5.0,"ph_max":7.5,"type":["sandy loam","loam"],"drainage":"well"}',60,'Low','Best green manure crop. Fixes 60-80 kg N/ha in 60 days. Suppresses nematodes.'),
('Sesbania aculeata','Dhaincha','cover','Green Manure','["Indian Subcontinent"]','{"temp_min":20,"temp_max":40,"rainfall_min":500,"rainfall_max":1200}','{"ph_min":4.5,"ph_max":8.0,"type":["clay","loam"],"drainage":"poor"}',50,'Medium','Fast-growing green manure. Tolerates waterlogging. Fixes 80-100 kg N/ha.'),
('Trifolium alexandrinum','Berseem (Egyptian Clover)','cover','Fodder','["Mediterranean","India"]','{"temp_min":10,"temp_max":25,"rainfall_min":400,"rainfall_max":800}','{"ph_min":6.0,"ph_max":7.5,"type":["clay loam"],"drainage":"well"}',150,'Medium','Best Rabi fodder. 4-6 cuts per season. Protein-rich livestock feed. Nitrogen-fixing.');

-- 6: FUNGI (3 plants)
INSERT INTO plant_directory (botanical_name, common_name, category, sub_category, origin_regions, optimal_climate, soil_requirements, growth_cycle_days, water_needs, description) VALUES
('Pleurotus ostreatus','Oyster Mushroom','fungi','Edible','["Temperate worldwide"]','{"temp_min":15,"temp_max":25,"rainfall_min":0,"rainfall_max":0}','{"ph_min":6.0,"ph_max":7.0,"type":["substrate:straw","substrate:sawdust"],"drainage":"well"}',21,'High humidity','Fast-growing. Cultivated on agricultural waste. 500g yield per kg dry straw.'),
('Agaricus bisporus','Button Mushroom','fungi','Edible','["Europe","North America"]','{"temp_min":15,"temp_max":22,"rainfall_min":0,"rainfall_max":0}','{"ph_min":7.0,"ph_max":7.5,"type":["substrate:compost"],"drainage":"well"}',45,'High humidity','Most widely cultivated mushroom. Requires composted substrate. White and brown varieties.'),
('Rhizophagus irregularis','Mycorrhizal Inoculant','fungi','Symbiote','["Global"]','{"temp_min":10,"temp_max":35,"rainfall_min":0,"rainfall_max":0}','{"ph_min":5.0,"ph_max":8.0,"type":["all"],"drainage":"all"}',0,'N/A','Forms symbiosis with 80% of plants. Boosts phosphorus uptake by 40-60%.');

-- 7: ALGAE (2 plants)
INSERT INTO plant_directory (botanical_name, common_name, category, sub_category, origin_regions, optimal_climate, soil_requirements, growth_cycle_days, water_needs, description) VALUES
('Arthrospira platensis','Spirulina','algae','Food Supplement','["Africa","Asia"]','{"temp_min":25,"temp_max":38,"rainfall_min":0,"rainfall_max":0}','{"ph_min":9.0,"ph_max":10.5,"type":["water:alkaline"],"drainage":"pond"}',10,'Aquatic','Complete protein (60-70%). Contains all essential amino acids. Commercial ponds in Tamil Nadu and Odisha.'),
('Chlorella vulgaris','Chlorella','algae','Bio-fertilizer','["Global freshwater"]','{"temp_min":20,"temp_max":30,"rainfall_min":0,"rainfall_max":0}','{"ph_min":6.0,"ph_max":8.0,"type":["water:freshwater"],"drainage":"pond"}',7,'Aquatic','Rich in chlorophyll. Used as bio-fertilizer and soil conditioner. Boosts seed germination by 20%.');

-- 8: AGRICULTURAL MICROBES (3 plants)
INSERT INTO plant_directory (botanical_name, common_name, category, sub_category, origin_regions, optimal_climate, soil_requirements, growth_cycle_days, water_needs, description) VALUES
('Rhizobium spp.','Rhizobium Inoculant','microbes','Nitrogen Fixer','["Global"]','{"temp_min":15,"temp_max":35,"rainfall_min":0,"rainfall_max":0}','{"ph_min":6.0,"ph_max":7.5,"type":["all"],"drainage":"all"}',0,'N/A','Symbiotic nitrogen fixer for legumes. 200g inoculant treats 10 kg seed. Increases pulse yield 15-25%.'),
('Bacillus megaterium','PSB (Phosphate Solubilizer)','microbes','Bio-fertilizer','["Global"]','{"temp_min":15,"temp_max":40,"rainfall_min":0,"rainfall_max":0}','{"ph_min":5.0,"ph_max":8.0,"type":["all"],"drainage":"all"}',0,'N/A','Converts locked soil phosphorus to plant-available form. Reduces DAP requirement by 25%. Soil application: 5 kg/ha.'),
('Trichoderma viride','Trichoderma Bio-fungicide','microbes','Bio-pesticide','["Global"]','{"temp_min":15,"temp_max":35,"rainfall_min":0,"rainfall_max":0}','{"ph_min":5.5,"ph_max":7.5,"type":["all"],"drainage":"all"}',0,'N/A','Controls root rot, wilt, damping-off. Natural antagonist to pathogenic fungi. Seed treatment: 4-8 g/kg seed.');

-- 9: LICHENS & MOSS (2 plants)
INSERT INTO plant_directory (botanical_name, common_name, category, sub_category, origin_regions, optimal_climate, soil_requirements, growth_cycle_days, water_needs, description) VALUES
('Cladonia rangiferina','Reindeer Moss','lichens','Bio-indicator','["Arctic","Temperate"]','{"temp_min":5,"temp_max":20,"rainfall_min":300,"rainfall_max":800}','{"ph_min":4.0,"ph_max":6.0,"type":["rock","bark"],"drainage":"well"}',365,'Low','Excellent air quality indicator. Absorbs pollutants. Used in terrariums and moss walls for moisture retention.'),
('Sphagnum spp.','Peat Moss','lichens','Moisture Retention','["Boreal","Temperate"]','{"temp_min":5,"temp_max":25,"rainfall_min":800,"rainfall_max":2000}','{"ph_min":3.5,"ph_max":5.0,"type":["bog"],"drainage":"poor"}',365,'Aquatic','Holds 20x its weight in water. Used in potting mixes, seed starting. Acidifies soil naturally. Harvest sustainably.');

-- 10: EXOTIC & RARE VARIETIES (5 plants)
INSERT INTO plant_directory (botanical_name, common_name, category, sub_category, exotic_variety, heirloom, origin_regions, optimal_climate, soil_requirements, growth_cycle_days, water_needs, description) VALUES
('Chenopodium quinoa','Quinoa','exotic','Pseudocereal',TRUE,TRUE,'["Andes","South America"]','{"temp_min":10,"temp_max":25,"rainfall_min":300,"rainfall_max":800}','{"ph_min":6.0,"ph_max":8.0,"type":["sandy loam"],"drainage":"well"}',120,'Low','Ancient Andean superfood. Complete protein. Now grown experimentally in Rajasthan and Uttarakhand.'),
('Salvia hispanica','Chia Seeds','exotic','Superfood',TRUE,TRUE,'["Mesoamerica"]','{"temp_min":15,"temp_max":30,"rainfall_min":400,"rainfall_max":800}','{"ph_min":6.0,"ph_max":7.5,"type":["sandy loam"],"drainage":"well"}',120,'Low-Medium','Rich in omega-3, fiber, protein. Grown commercially in Karnataka and Rajasthan under contract farming.'),
('Stevia rebaudiana','Stevia (Meethi Tulsi)','exotic','Natural Sweetener',TRUE,FALSE,'["Paraguay","Brazil"]','{"temp_min":15,"temp_max":30,"rainfall_min":1000,"rainfall_max":1500}','{"ph_min":6.0,"ph_max":7.5,"type":["loam","sandy loam"],"drainage":"well"}',60,'Medium','300x sweeter than sugar, zero calories. Thrives in Indian conditions. Leaf harvested every 45 days.'),
('Lagenaria siceraria','Bottle Gourd (Lauki) — Long Green','exotic','Heirloom Vegetable',FALSE,TRUE,'["Africa","India"]','{"temp_min":20,"temp_max":35,"rainfall_min":500,"rainfall_max":1000}','{"ph_min":6.0,"ph_max":7.5,"type":["loam","sandy loam"],"drainage":"well"}',60,'Medium','Heirloom long green variety. Non-hybrid. Seed-saving possible. Trellis growing for straight fruits.'),
('Solanum melongena','Brinjal — Black Beauty','exotic','Heirloom Vegetable',FALSE,TRUE,'["India"]','{"temp_min":20,"temp_max":32,"rainfall_min":600,"rainfall_max":1000}','{"ph_min":5.5,"ph_max":7.0,"type":["loam"],"drainage":"well"}',70,'Medium','Large glossy black fruit. Heirloom non-GMO variety. High market demand. Bihar native variety.');

-- 11: BIHAR HEIRLOOM & MAGAHI VARIETIES
INSERT INTO plant_directory (botanical_name, common_name, category, sub_category, exotic_variety, heirloom, origin_regions, optimal_climate, soil_requirements, growth_cycle_days, water_needs, description) VALUES
('Piper betle','Magahi Paan (Betel Leaf)','beverages','Heirloom Herb',FALSE,TRUE,'["Bihar","Magadh Region"]','{"temp_min":18,"temp_max":35,"rainfall_min":1000,"rainfall_max":2000}','{"ph_min":6.0,"ph_max":7.5,"type":["loam","clay loam"],"drainage":"well"}',180,'High','GI-tagged Magahi betel leaf from Magadh region of Bihar. Distinctive aroma and taste. Cultivated under shade nets in Nalanda, Nawada, and Gaya districts. A single vine produces 100-120 leaves per year.'),
('Oryza sativa','Katarani Rice (Magahi Red Rice)','staple','Heirloom Cereal',FALSE,TRUE,'["Bihar","Magadh"]','{"temp_min":22,"temp_max":35,"rainfall_min":1200,"rainfall_max":2000}','{"ph_min":5.5,"ph_max":7.0,"type":["clay","loam"],"drainage":"poor"}',140,'High','Ancient red rice variety native to Magadh region. Rust-colored grain with nutty flavor. Rich in anthocyanins and iron. Traditionally grown in lowland paddies of Nalanda and Gaya districts. Drought-resistant landrace.'),
('Euryale ferox','Desi Makhana (Fox Nut)','produce','Aquatic Crop',FALSE,TRUE,'["Bihar","North India"]','{"temp_min":20,"temp_max":35,"rainfall_min":1000,"rainfall_max":2000}','{"ph_min":6.0,"ph_max":8.0,"type":["clay","loam"],"drainage":"pond"}',240,'Aquatic','Bihar produces 90% of the world's makhana. Grown in freshwater ponds across Darbhanga, Madhubani, and Purnea. Popped seeds are a superfood — high protein, low fat. Harvested by skilled farmers wading through water.'),
('Solanum melongena','Bihar Heirloom Brinjal (Baigan)','produce','Heirloom Vegetable',FALSE,TRUE,'["Bihar","India"]','{"temp_min":20,"temp_max":32,"rainfall_min":600,"rainfall_max":1000}','{"ph_min":5.5,"ph_max":7.0,"type":["loam","sandy loam"],"drainage":"well"}',70,'Medium','Traditional Bihar variety — large, glossy purple-black fruits with green calyx. Non-GMO, non-hybrid. Sweet flesh with fewer seeds. Thrives in Gangetic plain conditions. Seed-saving possible.'),
('Oryza sativa','Sona Chur Rice (Golden Dust)','staple','Heirloom Aromatic',FALSE,TRUE,'["Bihar","West Bengal"]','{"temp_min":22,"temp_max":35,"rainfall_min":1000,"rainfall_max":1800}','{"ph_min":5.5,"ph_max":7.0,"type":["clay","loam"],"drainage":"poor"}',135,'High','Aromatic short-grain rice with golden hue when cooked. Traditional variety of Bihar and Bengal. Mild sweet fragrance. Ideal for khichdi, pulao, and festive dishes. Low yield but premium market price.');
-- Verify
SELECT category, count(*) as species FROM plant_directory GROUP BY category ORDER BY species DESC;
SELECT id, username, admin_tier FROM admin_users;
